FROM n8nio/runners:latest
USER root
RUN FILE=$(find / -name "n8n-task-runners.json" 2>/dev/null | head -1) && \
    sed -i 's/"N8N_RUNNERS_STDLIB_ALLOW": ""/"N8N_RUNNERS_STDLIB_ALLOW": "*"/g' $FILE && \
    sed -i 's/"N8N_RUNNERS_EXTERNAL_ALLOW": ""/"N8N_RUNNERS_EXTERNAL_ALLOW": "*"/g' $FILE
